#!/bin/sh

set -e

update-icon-caches /usr/share/icons/Gooroom-Flat-01 \
                   /usr/share/icons/Gooroom-Flat-02 \
                   /usr/share/icons/Gooroom-Flat-03 \
                   /usr/share/icons/Gooroom-Flat-04 \
                   /usr/share/icons/Gooroom-Flat-05
